<?php

/**
 * Implements hook_page_attachments().
 */
function cookieflag_page_attachments(&$attachments) {
  $attachments['#attached']['library'][] = 'cookieflag/cookieflag';

  $cookieflag_settings = \Drupal::state()->get('cookieflag_settings', []);
  $attachments['#attached']['drupalSettings']['cookieflag'] = $cookieflag_settings;
}

/**
 * Implements hook_theme().
 */
function cookieflag_theme(array &$settings) {

  return [
    'cookieflag_counter' => [
      'variables' => [],
      'template' => 'block--cookieflag-counter',
    ],
    'cookieflag_saved_page' => [
      'variables' => ['intro' => NULL, 'nodes' => NULL],
      'template' => 'cookieflag-saved-page',
    ],
  ];
}
